"""Organ-specific academic ML training for LifeLink-AI.

All generated datasets in this module are SYNTHETIC/ACADEMIC demonstration data.
They are not clinical datasets and are not clinically validated.
"""
from pathlib import Path
import json, time
import numpy as np
import pandas as pd
import joblib
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
try:
    from xgboost import XGBClassifier
except Exception:
    XGBClassifier=None
try:
    from lightgbm import LGBMClassifier
except Exception:
    LGBMClassifier=None

BASE=Path(__file__).resolve().parents[2]
DATASET_DIR=BASE/'datasets'
MODEL_DIR=Path(__file__).resolve().parent/'models'; MODEL_DIR.mkdir(exist_ok=True)
ORGANS=['kidney','liver','heart','lung']
TARGET='match_status'
CATEGORICAL=['donor_blood','recipient_blood','urgency']
NUMERIC=['donor_age','recipient_age','hla_match','antibody_risk','medical_risk','organ_health','waiting_days','cold_ischemia_hours','comorbidity_index','age_gap']
FEATURES=NUMERIC+CATEGORICAL


def _blood_pair_score(d,r):
    # Academic simplification only; intentionally not a clinical allocation rule.
    if d==r: return 1.0
    if d=='O': return 0.75
    if r=='AB': return 0.72
    return 0.25


def generate_dataset(organ, n=5000, seed=17):
    rng=np.random.default_rng(seed + ORGANS.index(organ)*101)
    donor_age=rng.integers(18,70,n); recipient_age=rng.integers(18,78,n)
    blood=np.array(['O','A','B','AB']); db=rng.choice(blood,n,p=[.45,.27,.23,.05]); rb=rng.choice(blood,n,p=[.40,.30,.25,.05])
    hla=rng.uniform(25,100,n); antibody=rng.uniform(0,100,n); medical=rng.uniform(0,100,n); health=rng.uniform(45,100,n)
    wait=rng.integers(1,1000,n); urgency=rng.choice(['Routine','Normal','Urgent','Critical'],n,p=[.12,.38,.34,.16])
    life={'kidney':24,'liver':12,'heart':6,'lung':6}[organ]
    cold=np.clip(rng.normal(life*.45,life*.18,n),0.5,life*1.8)
    comorb=np.clip(rng.poisson(2.0,n),0,8); age_gap=np.abs(donor_age-recipient_age)
    abo=np.array([_blood_pair_score(a,b) for a,b in zip(db,rb)])
    urgency_num=pd.Series(urgency).map({'Routine':1,'Normal':2,'Urgent':3,'Critical':4}).to_numpy()
    # Synthetic latent compatibility signal. No target-derived/post-outcome features are used.
    latent=(1.55*abo + .018*hla - .010*antibody - .009*medical + .006*health -.018*age_gap + .00055*wait + .12*urgency_num - .035*cold - .07*comorb + rng.normal(0,.55,n))
    threshold={'kidney':1.95,'liver':1.90,'heart':1.98,'lung':2.00}[organ]
    y=(latent>threshold).astype(int)
    # Add controlled missingness to exercise the preprocessing pipeline.
    miss=rng.random((n,len(FEATURES)))<0.006
    data={
      'donor_age':donor_age,'recipient_age':recipient_age,'hla_match':hla,'antibody_risk':antibody,
      'medical_risk':medical,'organ_health':health,'waiting_days':wait,'cold_ischemia_hours':cold,
      'comorbidity_index':comorb,'age_gap':age_gap,'donor_blood':db,'recipient_blood':rb,'urgency':urgency,
      TARGET:y
    }
    df=pd.DataFrame(data)
    for j,c in enumerate(FEATURES): df.loc[miss[:,j],c]=np.nan
    df['pair_id']=np.arange(1,n+1)
    return df


def ensure_datasets(n=5000):
    for i,organ in enumerate(ORGANS):
        d=DATASET_DIR/organ; d.mkdir(parents=True,exist_ok=True); path=d/f'{organ}_matching_synthetic_academic.csv'
        if not path.exists() or len(pd.read_csv(path))<n:
            generate_dataset(organ,n=n,seed=17).to_csv(path,index=False)


def load_task(task):
    task=task.lower();
    if task not in ORGANS: raise ValueError(f'Unsupported organ task: {task}')
    ensure_datasets(); path=DATASET_DIR/task/f'{task}_matching_synthetic_academic.csv'
    return pd.read_csv(path), f'Synthetic/Academic {task.title()} matching dataset (generated by LifeLink-AI)'


def load_heart(): return load_task('heart')

def _models():
    models={
      'Random Forest':RandomForestClassifier(n_estimators=180,max_depth=9,min_samples_leaf=3,class_weight='balanced',random_state=17,n_jobs=-1),
      'Gradient Boosting':GradientBoostingClassifier(n_estimators=120,max_depth=3,learning_rate=.04,min_samples_leaf=6,random_state=17)
    }
    if XGBClassifier:
        models['XGBoost']=XGBClassifier(n_estimators=160,max_depth=4,learning_rate=.04,min_child_weight=4,subsample=.85,colsample_bytree=.85,reg_lambda=2,eval_metric='logloss',random_state=17,n_jobs=1)
    if LGBMClassifier:
        models['LightGBM']=LGBMClassifier(n_estimators=160,num_leaves=23,max_depth=5,learning_rate=.04,min_child_samples=25,reg_lambda=2,verbose=-1,random_state=17,n_jobs=1)
    return models


def _preprocessor():
    return ColumnTransformer([
      ('num',Pipeline([('imp',SimpleImputer(strategy='median')),('sc',StandardScaler())]),NUMERIC),
      ('cat',Pipeline([('imp',SimpleImputer(strategy='most_frequent')),('oh',OneHotEncoder(handle_unknown='ignore'))]),CATEGORICAL)
    ])


def _prepare(df):
    X=df[FEATURES].copy(); y=pd.to_numeric(df[TARGET],errors='coerce').fillna(0).astype(int)
    return X,y


def _evaluate(task, df, source):
    X,y=_prepare(df)
    Xtr,Xte,ytr,yte=train_test_split(X,y,test_size=.20,random_state=17,stratify=y)
    cv=StratifiedKFold(n_splits=5,shuffle=True,random_state=17)
    rows=[]; fitted={}
    for name,model in _models().items():
        pipe=Pipeline([('prep',_preprocessor()),('model',model)])
        started=time.perf_counter(); pipe.fit(Xtr,ytr)
        proba=pipe.predict_proba(Xte)[:,1]; pred=(proba>=.5).astype(int)
        cvout=cross_validate(pipe,Xtr,ytr,cv=cv,scoring=['accuracy','precision','recall','f1','roc_auc'],n_jobs=1)
        auc=roc_auc_score(yte,proba) if len(np.unique(yte))==2 else 0.0
        row={'model':name,'accuracy':round(accuracy_score(yte,pred),4),'precision':round(precision_score(yte,pred,zero_division=0),4),'recall':round(recall_score(yte,pred,zero_division=0),4),'f1':round(f1_score(yte,pred,zero_division=0),4),'roc_auc':round(auc,4),'cv_accuracy':round(cvout['test_accuracy'].mean(),4),'cv_f1':round(cvout['test_f1'].mean(),4),'cv_roc_auc':round(cvout['test_roc_auc'].mean(),4),'cv_f1_std':round(cvout['test_f1'].std(),4),'training_seconds':round(time.perf_counter()-started,2),'confusion_matrix':confusion_matrix(yte,pred).tolist()}
        rows.append(row); fitted[name]=pipe
    best=max(rows,key=lambda r:(r['f1'],r['roc_auc'],r['accuracy']))
    joblib.dump(fitted[best['model']],MODEL_DIR/f'{task}_best.joblib')
    bundle={'schema_version':2,'task':task,'dataset':source,'source':source,'target':TARGET,'best_model':best['model'],'metrics':rows,'features':FEATURES,'categorical_features':CATEGORICAL,'numeric_features':NUMERIC,'rows':len(df),'class_balance':{str(k):int(v) for k,v in y.value_counts().sort_index().items()},'evaluation':'80/20 stratified holdout plus 5-fold stratified cross-validation; target leakage excluded; preprocessing fitted inside each pipeline; synthetic/academic data only','trained_at':pd.Timestamp.utcnow().isoformat()}
    joblib.dump(bundle,MODEL_DIR/f'{task}_metrics.joblib')
    return bundle


def train_all():
    ensure_datasets()
    bundles=[]
    for task in ORGANS:
        df,source=load_task(task); bundles.append(_evaluate(task,df,source))
    return {b['task']:b for b in bundles}


def get_bundle(task='heart'):
    task=task.lower()
    p=MODEL_DIR/f'{task}_metrics.joblib'
    if not p.exists(): return train_task(task)
    bundle=joblib.load(p)
    if bundle.get('schema_version') != 2 or bundle.get('target') != TARGET or bundle.get('rows',0) < 5000:
        return train_task(task)
    return bundle


def train_task(task):
    task=task.lower()
    if task not in ORGANS: task='kidney'
    return _evaluate(task,*load_task(task))
