from datetime import datetime
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False)
    email = db.Column(db.String(160), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    role = db.Column(db.String(30), nullable=False)
    hospital = db.Column(db.String(160))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class Donor(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False)
    organ = db.Column(db.String(40), nullable=False)
    blood_group = db.Column(db.String(5), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    hla_match = db.Column(db.Float, default=0)
    antibodies = db.Column(db.Float, default=0)
    medical_history = db.Column(db.Float, default=0)
    location = db.Column(db.String(160), nullable=False)
    harvest_hours = db.Column(db.Float, default=0)
    status = db.Column(db.String(30), default='REGISTERED', index=True)
    doctor_approval = db.Column(db.String(20), default='PENDING')
    hospital_approval = db.Column(db.String(20), default='PENDING')
    admin_approval = db.Column(db.String(20), default='PENDING')
    consent = db.Column(db.String(20), default='PENDING')
    approved_by_doctor = db.Column(db.Integer, db.ForeignKey('user.id'))
    approved_by_hospital = db.Column(db.Integer, db.ForeignKey('user.id'))
    approved_by_admin = db.Column(db.Integer, db.ForeignKey('user.id'))
    doctor_decided_at = db.Column(db.DateTime)
    hospital_decided_at = db.Column(db.DateTime)
    admin_decided_at = db.Column(db.DateTime)
    rejection_reason = db.Column(db.Text)
    available_at = db.Column(db.DateTime)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class Recipient(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False)
    organ = db.Column(db.String(40), nullable=False)
    blood_group = db.Column(db.String(5), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    hla_match = db.Column(db.Float, default=0)
    antibodies = db.Column(db.Float, default=0)
    medical_history = db.Column(db.Float, default=0)
    waiting_days = db.Column(db.Integer, default=0)
    location = db.Column(db.String(160), nullable=False)
    urgency = db.Column(db.String(20), default='Normal')
    status = db.Column(db.String(30), default='RECIPIENT_REGISTERED', index=True)
    doctor_approval = db.Column(db.String(20), default='PENDING')
    consent = db.Column(db.String(20), default='PENDING')
    approved_by_doctor = db.Column(db.Integer, db.ForeignKey('user.id'))
    doctor_decided_at = db.Column(db.DateTime)
    rejection_reason = db.Column(db.Text)
    activated_at = db.Column(db.DateTime)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class Match(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    donor_id = db.Column(db.Integer, db.ForeignKey('donor.id'), nullable=False)
    recipient_id = db.Column(db.Integer, db.ForeignKey('recipient.id'), nullable=False)
    score = db.Column(db.Float, nullable=False)
    ml_score = db.Column(db.Float, default=0)
    confidence = db.Column(db.Float, default=0)
    priority_score = db.Column(db.Float, default=0)
    risk_level = db.Column(db.String(20), default='MEDIUM')
    match_breakdown = db.Column(db.Text)
    model = db.Column(db.String(80), default='Best ML Model')
    explanation = db.Column(db.Text)
    shap_data = db.Column(db.Text)
    status = db.Column(db.String(40), default='Recommended')
    workflow_state = db.Column(db.String(40), default='DOCTOR_PENDING', index=True)
    doctor_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    doctor_decision = db.Column(db.String(20))
    doctor_reason = db.Column(db.Text)
    doctor_decided_at = db.Column(db.DateTime)
    hospital_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    hospital_decision = db.Column(db.String(20))
    hospital_reason = db.Column(db.Text)
    hospital_decided_at = db.Column(db.DateTime)
    admin_verified_by = db.Column(db.Integer, db.ForeignKey('user.id'))
    admin_verified_at = db.Column(db.DateTime)
    admin_reason = db.Column(db.Text)
    recipient_selected = db.Column(db.Boolean, default=False)
    selected_at = db.Column(db.DateTime)
    final_status = db.Column(db.String(40), default='CANDIDATE')
    completed_at = db.Column(db.DateTime)
    reviewed_by = db.Column(db.String(160))
    reviewed_at = db.Column(db.DateTime)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    donor = db.relationship('Donor')
    recipient = db.relationship('Recipient')
    doctor = db.relationship('User', foreign_keys=[doctor_id])
    hospital_user = db.relationship('User', foreign_keys=[hospital_id])
    admin_user = db.relationship('User', foreign_keys=[admin_verified_by])

class MatchRequest(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    match_id = db.Column(db.Integer, db.ForeignKey('match.id'), nullable=False, unique=True)
    donor_id = db.Column(db.Integer, db.ForeignKey('donor.id'), nullable=False)
    recipient_id = db.Column(db.Integer, db.ForeignKey('recipient.id'), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    recipient_status = db.Column(db.String(20), default='ACCEPTED')
    donor_status = db.Column(db.String(20), default='PENDING')
    doctor_status = db.Column(db.String(20), default='PENDING')
    hospital_status = db.Column(db.String(20), default='PENDING')
    admin_status = db.Column(db.String(20), default='PENDING')
    final_status = db.Column(db.String(40), default='DONOR_PENDING')
    donor_decided_at = db.Column(db.DateTime)
    doctor_decided_at = db.Column(db.DateTime)
    hospital_decided_at = db.Column(db.DateTime)
    admin_decided_at = db.Column(db.DateTime)
    rejection_reason = db.Column(db.Text)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    match = db.relationship('Match', backref=db.backref('match_request', uselist=False))
    donor = db.relationship('Donor')
    recipient = db.relationship('Recipient')


class Transport(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    match_id = db.Column(db.Integer, db.ForeignKey('match.id'), nullable=False)
    source = db.Column(db.String(160), nullable=False)
    destination = db.Column(db.String(160), nullable=False)
    distance = db.Column(db.Float, default=0)
    eta = db.Column(db.Float, default=0)
    estimated_minutes = db.Column(db.Float, default=0)
    max_allowed_minutes = db.Column(db.Float, default=0)
    remaining_minutes = db.Column(db.Float, default=0)
    feasible = db.Column(db.Boolean, default=False)
    traffic_condition = db.Column(db.String(30), default='Configured/static')
    departure_at = db.Column(db.DateTime)
    eta_at = db.Column(db.DateTime)
    actual_arrival_at = db.Column(db.DateTime)
    transport_provider = db.Column(db.String(160))
    transport_mode = db.Column(db.String(40), default='GROUND')
    route_risk = db.Column(db.Float, default=0)
    notes = db.Column(db.Text)
    alternatives = db.Column(db.Text)
    algorithm = db.Column(db.String(80))
    route_nodes = db.Column(db.Text)
    route_points = db.Column(db.Text)
    status = db.Column(db.String(30), default='Planned')
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    match = db.relationship('Match')

class AuditLog(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    action = db.Column(db.String(160), nullable=False)
    entity = db.Column(db.String(80))
    entity_id = db.Column(db.Integer)
    details = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    user = db.relationship('User')


class UserProfile(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), unique=True, nullable=False)
    phone = db.Column(db.String(30))
    address = db.Column(db.String(255))
    government_id = db.Column(db.String(120))
    hospital_registration = db.Column(db.String(120))
    donor_id = db.Column(db.Integer, db.ForeignKey('donor.id'))
    recipient_id = db.Column(db.Integer, db.ForeignKey('recipient.id'))
    verification_status = db.Column(db.String(30), default='Pending')
    account_status = db.Column(db.String(30), default='Active')
    risk_score = db.Column(db.Integer, default=0)
    last_login = db.Column(db.DateTime)
    last_ip = db.Column(db.String(80))
    failed_logins = db.Column(db.Integer, default=0)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    user = db.relationship('User', backref=db.backref('profile', uselist=False))
    donor = db.relationship('Donor', foreign_keys=[donor_id])
    recipient = db.relationship('Recipient', foreign_keys=[recipient_id])

class SecurityEvent(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    event_type = db.Column(db.String(80), nullable=False)
    severity = db.Column(db.String(20), default='Low')
    risk_score = db.Column(db.Integer, default=0)
    ip_address = db.Column(db.String(80))
    details = db.Column(db.Text)
    resolved = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    user = db.relationship('User')


class TransportEvent(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    transport_id = db.Column(db.Integer, db.ForeignKey('transport.id'), nullable=False)
    status = db.Column(db.String(40), nullable=False)
    changed_by = db.Column(db.Integer, db.ForeignKey('user.id'))
    notes = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    transport = db.relationship('Transport')
    user = db.relationship('User')


class Notification(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    title = db.Column(db.String(180), nullable=False)
    message = db.Column(db.Text, nullable=False)
    category = db.Column(db.String(40), default='INFO')
    reference_type = db.Column(db.String(40))
    reference_id = db.Column(db.Integer)
    is_read = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    user = db.relationship('User')

class HospitalCapability(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    hospital_user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    organ = db.Column(db.String(40), nullable=False)
    transplant_capable = db.Column(db.Boolean, default=True)
    emergency_transport = db.Column(db.Boolean, default=True)
    storage_capable = db.Column(db.Boolean, default=True)
    max_daily_cases = db.Column(db.Integer, default=10)
    user = db.relationship('User')

class ModelExperiment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    model_name = db.Column(db.String(80), nullable=False)
    dataset = db.Column(db.String(120), nullable=False)
    accuracy = db.Column(db.Float, default=0)
    precision = db.Column(db.Float, default=0)
    recall = db.Column(db.Float, default=0)
    f1 = db.Column(db.Float, default=0)
    roc_auc = db.Column(db.Float, default=0)
    std_f1 = db.Column(db.Float, default=0)
    training_seconds = db.Column(db.Float, default=0)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class WhatIfRun(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    match_id = db.Column(db.Integer, db.ForeignKey('match.id'))
    changes = db.Column(db.Text)
    before_score = db.Column(db.Float)
    after_score = db.Column(db.Float)
    explanation = db.Column(db.Text)
    created_by = db.Column(db.Integer, db.ForeignKey('user.id'))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    match = db.relationship('Match')
    user = db.relationship('User')


class DatasetArtifact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    filename = db.Column(db.String(255), nullable=False)
    stored_path = db.Column(db.String(255), nullable=False)
    rows = db.Column(db.Integer, default=0)
    columns = db.Column(db.Integer, default=0)
    missing_values = db.Column(db.Integer, default=0)
    validation_status = db.Column(db.String(30), default='VALIDATED')
    uploaded_by = db.Column(db.Integer, db.ForeignKey('user.id'))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    user = db.relationship('User')
